"""Generate ``docs/reference/input-formats.md`` from the extension registry.

The extension vocabulary is single-sourced in
``portolan_cli.extension_registry`` (ADR-0055). This script renders it as the
human-facing input-formats reference page, replacing the hand-written
extensions doc from the removed vendored spec folder (#751). Regenerate after
any registry change:

    uv run python scripts/gen_input_formats_doc.py

``tests/unit/test_input_formats_doc.py`` fails while the page is stale.
"""

from __future__ import annotations

from pathlib import Path

from portolan_cli.extension_registry import (
    EXTENSION_REGISTRY,
    SIDECAR_OF,
    ExtensionSpec,
)

_DOC_PATH = Path(__file__).resolve().parents[1] / "docs" / "reference" / "input-formats.md"

_CLOUD_NATIVE_LABEL = {
    "yes": "Yes",
    "inspect": "Content-inspected",
    "no": "No",
}


def _geo_row(spec: ExtensionSpec) -> str:
    name = spec.display_name or spec.ext.lstrip(".").upper()
    converts = spec.convert_target or "—"
    notes: list[str] = []
    if spec.is_dir:
        notes.append("directory format")
    if spec.is_compound:
        notes.append("compound extension")
    if spec.is_multilayer:
        notes.append("multi-layer; every layer converts")
    if spec.is_tabular:
        notes.append("tabular when no geometry is found")
    return (
        f"| `{spec.ext}` | {name} | {spec.routes_as or '—'} | "
        f"{_CLOUD_NATIVE_LABEL[spec.cloud_native]} | {converts} | {', '.join(notes) or '—'} |"
    )


def _typed_row(spec: ExtensionSpec) -> str:
    name = spec.display_name or spec.ext.lstrip(".").upper()
    return f"| `{spec.ext}` | {name} | {spec.media_type or '—'} | {spec.unsupported_message} |"


def _category_rows(category: str) -> list[str]:
    return [
        f"| `{spec.ext}` | {spec.media_type or '—'} | {spec.role or '—'} |"
        for spec in EXTENSION_REGISTRY
        if spec.scan_category == category
    ]


def render() -> str:
    """Render the full input-formats page as markdown."""
    lines: list[str] = [
        "# Input Formats",
        "",
        "<!-- Generated by scripts/gen_input_formats_doc.py from",
        "     portolan_cli/extension_registry.py (ADR-0055). Do not edit by hand;",
        "     edit the registry and regenerate. -->",
        "",
        "Portolan classifies input files by extension when you run `portolan scan`",
        "or `portolan add`. The vocabulary below is generated from the typed",
        "registry in `portolan_cli/extension_registry.py`, the single source of",
        "truth for how each extension is recognized, routed, and converted.",
        "",
        "Formats marked *Content-inspected* need a look inside the file: a",
        "`.parquet` is GeoParquet only if it carries `geo` metadata, a `.tif` is",
        "cloud-native only if it is a valid COG, and a `.csv`/`.tsv` routes to the",
        "vector pipeline only when geometry columns are found (otherwise it is",
        "tabular data, which requires `tabular.enabled: true`).",
        "",
        "## Geospatial and Cloud-Native Data",
        "",
        "| Extension | Format | Routes As | Cloud-Native | Converts To | Notes |",
        "|-----------|--------|-----------|--------------|-------------|-------|",
    ]
    lines += [
        _geo_row(spec)
        for spec in EXTENSION_REGISTRY
        if spec.is_geospatial or spec.cloud_native in ("yes", "inspect")
    ]
    lines += [
        "",
        "Non-cloud-native formats are accepted with a conversion warning",
        "(ADR-0014); Portolan converts vectors to GeoParquet and rasters to COG.",
        "",
        "## Tabular Data",
        "",
        "Tabular (non-geospatial) support is opt-in (ADR-0047).",
        "",
        "| Extension | Format | Media Type | Notes |",
        "|-----------|--------|------------|-------|",
    ]
    for spec in EXTENSION_REGISTRY:
        if spec.is_tabular:
            name = spec.display_name or spec.ext.lstrip(".").upper()
            note = (
                "routes to the vector pipeline when geometry is present"
                if spec.is_geospatial
                else "tabular only"
            )
            lines.append(f"| `{spec.ext}` | {name} | {spec.media_type or '—'} | {note} |")
    lines += [
        "",
        "## Unsupported Formats",
        "",
        "These are recognized and rejected with a specific message rather than",
        "silently ignored.",
        "",
        "| Extension | Format | Media Type | Message |",
        "|-----------|--------|------------|---------|",
    ]
    lines += [_typed_row(spec) for spec in EXTENSION_REGISTRY if spec.unsupported_message]
    lines += [
        "",
        "## Sidecar Files",
        "",
        "Sidecars ride along with a primary file and are tracked as assets of it.",
        "",
        "| Extension | Media Type | Role |",
        "|-----------|------------|------|",
    ]
    lines += _category_rows("known_sidecar")
    lines += [
        "",
        "Per-primary sidecar patterns (matched against the primary file's stem):",
        "",
        "| Primary | Sidecar Suffixes |",
        "|---------|------------------|",
    ]
    lines += [
        f"| `{primary}` | {', '.join(f'`{s}`' for s in suffixes)} |"
        for primary, suffixes in SIDECAR_OF.items()
    ]
    lines += [
        "",
        "## Documentation, Thumbnails, and Visualization",
        "",
        "| Extension | Media Type | Role |",
        "|-----------|------------|------|",
    ]
    lines += _category_rows("documentation")
    lines += _category_rows("thumbnail")
    lines += _category_rows("visualization")
    lines += [
        f"| `{spec.ext}` | {spec.media_type or '—'} | {spec.role or '—'} |"
        for spec in EXTENSION_REGISTRY
        if spec.scan_category is None and spec.role in ("metadata", "documentation")
    ]
    lines += [
        "",
        "## Ignored",
        "",
        "Build artifacts and binaries are classified as junk and never tracked.",
        "",
        "| Extension | Media Type | Role |",
        "|-----------|------------|------|",
    ]
    lines += _category_rows("junk")
    lines += [
        "",
        "Aliases that participate only in media-type and role maps (never in",
        "format detection):",
        "",
        "| Extension | Media Type | Role |",
        "|-----------|------------|------|",
    ]
    lines += [
        f"| `{spec.ext}` | {spec.media_type or '—'} | {spec.role or '—'} |"
        for spec in EXTENSION_REGISTRY
        if spec.scan_category is None
        and not spec.is_geospatial
        and spec.cloud_native == "no"
        and not spec.is_tabular
        and not spec.unsupported_message
        and spec.role not in ("metadata", "documentation")
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    _DOC_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {_DOC_PATH}")  # noqa: T201


if __name__ == "__main__":
    main()
