"""Generate the public CLI, Python API, and configuration reference wrappers.

The generated pages expose only Portolan's supported public API. Run this
script after changing the Click tree, either package export list, or the
conversion settings dataclasses.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

import click

import portolan_cli
import portolan_cli.backends
from portolan_cli.conversion_config import (
    VALID_SORT_METHODS,
    VALID_SPATIAL_INDEXES,
    VectorSettings,
)


def _command_names(command: click.Command, prefix: str = "") -> list[str]:
    """Return the complete command tree in deterministic display order."""
    if not isinstance(command, click.Group):
        return []

    names: list[str] = []
    for name in sorted(command.commands):
        child = command.commands[name]
        full_name = f"{prefix} {name}".strip()
        names.append(full_name)
        names.extend(_command_names(child, full_name))
    return names


def _cli_reference() -> str:
    """Build the MkDocs wrapper for the shipped Click tree."""
    commands = "\n".join(f"- `portolan {name}`" for name in _command_names(portolan_cli.cli))
    return f"""# CLI Reference

<!-- Generated by scripts/generate_reference_docs.py. Do not edit. -->

This page is generated from the shipped Click command tree.

## Commands

{commands}

## Full Reference

::: mkdocs-click
    :module: portolan_cli.cli
    :command: cli
    :prog_name: portolan
    :depth: 2
    :style: table
    :show_hidden: false
"""


def _api_reference() -> str:
    """Build the MkDocs wrapper for the explicit supported Python exports."""
    top_level = "\n".join(f"::: portolan_cli.{name}\n" for name in portolan_cli.__all__)
    backends = "\n".join(
        f"::: portolan_cli.backends.{name}\n" for name in portolan_cli.backends.__all__
    )
    return f"""# Python API Reference

<!-- Generated by scripts/generate_reference_docs.py. Do not edit. -->

This page documents the supported Python API. Internal modules are not a
supported interface.

## Top-Level Exports

{top_level}
## Backend Plugin Interface

{backends}"""


def _reference_index() -> str:
    """Build the generated Reference navigation landing page."""
    return """# Reference

<!-- Generated by scripts/generate_reference_docs.py. Do not edit. -->

- [CLI Reference](cli.md)
- [Python API Reference](python.md)
- [Configuration Reference](configuration.md)
"""


def _configuration_reference() -> str:
    """Build the conversion configuration reference from the shipped defaults.

    Every default is read from :class:`VectorSettings` rather than written out,
    so a change to the dataclass cannot leave the page stale (issue #805).
    """
    defaults = VectorSettings()
    # A literal pipe would end the table cell, so the alternatives are escaped.
    indexes = r" \| ".join(sorted(VALID_SPATIAL_INDEXES))
    sorts = r" \| ".join(sorted(VALID_SORT_METHODS))
    rows = "\n".join(
        [
            f"| `spatial_index` | {indexes} | `{defaults.spatial_index}` |"
            " Spatial index column to add. |",
            f"| `resolution` | auto \\| integer | `{defaults.resolution}` |"
            " Index resolution. `auto` uses the geoparquet-io defaults. |",
            f"| `sort` | {sorts} | `{defaults.sort}` | Row ordering method. |",
            f"| `add_bbox` | true \\| false | `{str(defaults.add_bbox).lower()}` |"
            " Add a bbox covering column. |",
            f"| `partition` | true \\| false | `{str(defaults.partition).lower()}` |"
            " Produce hive-partitioned output. Requires a spatial index. |",
        ]
    )
    return f"""# Configuration Reference

<!-- Generated by scripts/generate_reference_docs.py. Do not edit. -->

Portolan reads catalog settings from `.portolan/config.yaml`.

## Vector Conversion

The `conversion.vector` block controls how Portolan writes GeoParquet.

| Setting | Values | Default | Meaning |
|---------|--------|---------|---------|
{rows}

```yaml
conversion:
  vector:
    sort: {defaults.sort}
    add_bbox: {str(defaults.add_bbox).lower()}
```

## Conforming Output by Default

`sort` and `add_bbox` carry the values the Portolan GeoParquet profile
requires. rashid reads both `PTL-DAT-006` and `PTL-DAT-007` through the bbox
covering column, so a file without that column fails `portolan check`. Set
`sort: none` or `add_bbox: false` to turn either off.

These settings apply to `portolan add` and `portolan convert`. `portolan
extract arcgis` always writes the covering column and does not read this
block.

`add` also rewrites a GeoParquet you hand it when that file carries no
covering column. A file that already has one is copied untouched, so a large
conformant file costs nothing. `--force` applies the same test.

The rewrite is a full read, sort, and write, not a copy. `add` reports the
file size before it starts, and it needs free space for a second copy of the
file while it runs. Above 1GB `add` also prints a warning, because the read
and the sort take long enough to look like a stall. Every schema metadata key
the file carried is restored afterwards, `pandas` and publisher keys included.

## The Rewrite Never Loses Data

`add` compares the rewritten file against the source before it swaps them in.
It checks the row count, the column set, and the declared CRS. It keeps your
file and prints the reason when any of those would be lost. The file then
stays non-conformant, and `check` reports it. A projected GeoParquet keeps its
CRS through the rewrite:

```console
$ portolan add roads/data.parquet
→ Rewriting data.parquet (11.1KB): it carries no bbox covering column
✓ Added 1 file to 1 collection
```

`add` does not inspect row order. To reorder a file that has the column but is
not sorted, run `portolan add <path> --force --reconvert`. That is also the
way to apply `sort` to an existing file when you set `add_bbox: false`,
because the footer then shows nothing `add` can act on.
"""


def generated_pages(project_root: Path) -> dict[Path, str]:
    """Return generated reference pages, keyed by project-relative path."""
    _ = project_root
    return {
        Path("docs/reference/cli.md"): _cli_reference(),
        Path("docs/reference/python.md"): _api_reference(),
        Path("docs/reference/configuration.md"): _configuration_reference(),
        Path("docs/reference/index.md"): _reference_index(),
    }


def _write_pages(project_root: Path) -> None:
    """Write every generated page to the repository."""
    for relative_path, content in generated_pages(project_root).items():
        target = project_root / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def _check_pages(project_root: Path) -> bool:
    """Return whether every checked-in generated page is current."""
    is_current = True
    for relative_path, expected in generated_pages(project_root).items():
        target = project_root / relative_path
        actual = target.read_text(encoding="utf-8") if target.exists() else ""
        if actual != expected:
            print(f"Generated reference is stale: {relative_path}", file=sys.stderr)
            is_current = False
    return is_current


def main(argv: Sequence[str] | None = None) -> int:
    """Generate reference wrappers or report stale checked-in output."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated reference pages differ from checked-in files.",
    )
    arguments = parser.parse_args(argv)
    project_root = Path(__file__).resolve().parents[1]

    if arguments.check:
        return 0 if _check_pages(project_root) else 1

    _write_pages(project_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
