"""Generate the public CLI and Python API reference wrappers.

The generated pages expose only Portolan's supported public API. Run this
script after changing the Click tree or either package export list.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

import click

import portolan_cli
import portolan_cli.backends


def _command_names(command: click.Command, prefix: str = "") -> list[str]:
    """Return the complete command tree in deterministic display order."""
    if not isinstance(command, click.Group):
        return []

    names: list[str] = []
    for name in sorted(command.commands):
        child = command.commands[name]
        full_name = f"{prefix} {name}".strip()
        names.append(full_name)
        names.extend(_command_names(child, full_name))
    return names


def _cli_reference() -> str:
    """Build the MkDocs wrapper for the shipped Click tree."""
    tick = chr(96)
    commands = "\n".join(
        f"- {tick}portolan {name}{tick}" for name in _command_names(portolan_cli.cli)
    )
    return f"""# CLI Reference

<!-- Generated by scripts/generate_reference_docs.py. Do not edit. -->

This page is generated from the shipped Click command tree.

## Commands

{commands}

## Full Reference

::: mkdocs-click
    :module: portolan_cli.cli
    :command: cli
    :prog_name: portolan
    :depth: 2
    :style: table
    :show_hidden: false
"""


def _api_reference() -> str:
    """Build the MkDocs wrapper for the explicit supported Python exports."""
    top_level = "\n".join(f"::: portolan_cli.{name}\n" for name in portolan_cli.__all__)
    backends = "\n".join(
        f"::: portolan_cli.backends.{name}\n" for name in portolan_cli.backends.__all__
    )
    return f"""# Python API Reference

<!-- Generated by scripts/generate_reference_docs.py. Do not edit. -->

This page documents the supported Python API. Internal modules are not a
supported interface.

## Top-Level Exports

{top_level}
## Backend Plugin Interface

{backends}"""


def _reference_index() -> str:
    """Build the generated Reference navigation landing page."""
    return """# Reference

<!-- Generated by scripts/generate_reference_docs.py. Do not edit. -->

- [CLI Reference](cli.md)
- [Python API Reference](python.md)
"""


def generated_pages(project_root: Path) -> dict[Path, str]:
    """Return generated reference pages, keyed by project-relative path."""
    _ = project_root
    return {
        Path("docs/reference/cli.md"): _cli_reference(),
        Path("docs/reference/python.md"): _api_reference(),
        Path("docs/reference/index.md"): _reference_index(),
    }


def _write_pages(project_root: Path) -> None:
    """Write every generated page to the repository."""
    for relative_path, content in generated_pages(project_root).items():
        target = project_root / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def _check_pages(project_root: Path) -> bool:
    """Return whether every checked-in generated page is current."""
    is_current = True
    for relative_path, expected in generated_pages(project_root).items():
        target = project_root / relative_path
        actual = target.read_text(encoding="utf-8") if target.exists() else ""
        if actual != expected:
            print(f"Generated reference is stale: {relative_path}", file=sys.stderr)
            is_current = False
    return is_current


def main(argv: Sequence[str] | None = None) -> int:
    """Generate reference wrappers or report stale checked-in output."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated reference pages differ from checked-in files.",
    )
    arguments = parser.parse_args(argv)
    project_root = Path(__file__).resolve().parents[1]

    if arguments.check:
        return 0 if _check_pages(project_root) else 1

    _write_pages(project_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
